### ISSUE TITLE
yo r u making a watch?

### ISSUE THREAD

**Issue by bezark** [samheckle/watchy-resources#1]

**Comment by bezark** [comment]
### @samheckle I NEED TO KNOW

**Comment by samheckle** [comment]
omg

**Comment by samheckle** [comment]
i have a watch if you want to play with it

**Comment by samheckle** [comment]
@bezark

**Comment by bezark** [comment]
Hell yeah I do! Lol

**Comment by samheckle** [comment]
ok come to my house also they have a [discord](https://discord.com/invite/ZXDegGV8E7) if you didn't join already
